package com.jtc.credit.dto;

// Generated Oct 29, 2014 11:20:20 AM by Hibernate Tools 3.4.0.CR1

/**
 * BpsSetting generated by hbm2java
 */
public class TapiPrice implements java.io.Serializable {
	
	private static final long serialVersionUID = -8607588979712724852L;
	private Integer id;
	private String groupName;
	private String apiName;
	private double price;
	private String descr;
	private boolean status;

	public TapiPrice() {
	}
	
	public TapiPrice(Integer id,String groupName,String apiName,String descr,double price, boolean status) {
		this.id = id;
		this.groupName = groupName;
		this.apiName = apiName;
		this.descr = descr;
		this.price = price;
		this.status = status;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getApiName() {
		return apiName;
	}

	public void setApiName(String apiName) {
		this.apiName = apiName;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getDescr() {
		return descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	

}
